import Link from 'next/link'
import { Badge, Button, Card } from '@/components/ui'

const proof = ['Typed domain model', 'Interactive dashboard', 'Client-ready reports', 'Deploy-safe routes']

export default function HomePage() {
  return (
    <main className="min-h-screen bg-zinc-50">
      <section className="border-b border-zinc-200 bg-white px-6 py-16">
        <div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div>
            <Badge tone="success">Generated by NEXUS OS</Badge>
            <h1 className="mt-5 max-w-3xl text-4xl font-black tracking-tight text-zinc-950 sm:text-6xl">Youtube Os Automated Channel Growth Engine</h1>
            <p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-600">
              A polished SaaS operating workspace with measurable workflow states, risk handling, analytics, and a client-ready dashboard built for real buyer evaluation.
            </p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row">
              <Link href="/dashboard"><Button type="button">Open command center</Button></Link>
              <Link href="/dashboard/operating-queue"><Button type="button" variant="secondary">Review queue</Button></Link>
            </div>
          </div>
          <Card className="p-6">
            <div className="grid gap-3">
              {proof.map((item, index) => (
                <div key={item} className="flex items-center justify-between rounded-lg border border-zinc-200 bg-zinc-50 p-4">
                  <span className="font-semibold text-zinc-800">{item}</span>
                  <Badge tone={index < 2 ? 'success' : 'info'}>{index < 2 ? 'Ready' : 'Included'}</Badge>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </section>
    </main>
  )
}
