import Link from 'next/link'
import { Badge, Button } from '@/components/ui'
import { navItems } from '@/lib/data'

export function DemoBanner() {
  return (
    <div className="border-b border-zinc-200 bg-white px-4 py-2 text-center text-xs font-semibold text-zinc-600">
      Professional MVP generated by NEXUS OS with typed data, workflow states, reports, and deploy-safe routes.
    </div>
  )
}

export function AppSidebar() {
  return (
    <aside className="hidden min-h-screen w-72 border-r border-zinc-200 bg-zinc-950 p-5 text-white lg:block">
      <div className="mb-8">
        <p className="text-xs font-semibold uppercase tracking-[0.24em] text-lime-300">NEXUS OS</p>
        <h1 className="mt-2 text-xl font-black leading-tight">Youtube Os Automated Channel Growth Engine</h1>
        <Badge className="mt-3 bg-white/10 text-zinc-200 ring-1 ring-white/15">Production preview</Badge>
      </div>
      <nav className="space-y-1">
        {navItems.map(item => (
          <Link key={item.href} href={item.href} className="flex items-center justify-between rounded-lg px-3 py-2 text-sm font-medium text-zinc-300 hover:bg-white/10 hover:text-white">
            <span>{item.label}</span>
            {item.badge && <span className="rounded-full bg-lime-300 px-2 py-0.5 text-xs font-black text-zinc-950">{item.badge}</span>}
          </Link>
        ))}
      </nav>
    </aside>
  )
}

export function AppHeader() {
  return (
    <header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/90 px-4 py-3 backdrop-blur">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-bold text-zinc-950">Youtube Os Automated Channel Growth Engine</p>
          <p className="text-xs text-zinc-500">Command center · live operating model</p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" type="button">Export</Button>
          <Button type="button">New workflow</Button>
        </div>
      </div>
    </header>
  )
}
